In [1]:
str1 = "geek"
str2 = "gesek"

In [4]:
def edit_dist(str1, str2):
    cost = 0
    if len(str1) == len(str2):
        # replace
        for i in range(0 , len(str1)):
            if str1[i] == str2[i] :
                print("No edits required")
                break
            else:
                cost = cost + 1
                print("Replace required")
        
    if len(str1) > len(str2) or len(str1) < len(str2):
        print("Removing required")
        cost = cost + 1
        
        
        #insert
        #OR
        #Remove
    return cost
        
        

In [5]:
edit_dist(str1, str2)

Removing required


1

In [109]:
# USING Dynamic Programming

def dp_edit_dist(str1, str2):
    m = len(str1) + 1
    n = len(str2) + 1
    
    rows = m
    cols = n
    
    dp = [[0] *cols ]*rows 
#     print(dp)
    
    for i in range(rows):
        for j in range(cols):
            if i == 0:
                dp[i][j] = j
            elif j == 0:
                dp[i][j] = i
            elif str1[i-1] == str2[j-1]:
                dp[i][j] = dp[i-1][j-1]
            else:
                dp[i][j] = 1 + min(dp[i-1][j-1] , 
                                   dp[i-1][j] , 
                                   dp[i][j-1])

        
    return dp
    
    

In [110]:
str1 = "geek"
str2 = "gesek"

# dp = np.asarray(dp_edit_dist(str1, str2))
dp_edit_dist(str1, str2)
# dp

[[4, 4, 4, 5, 5, 5],
 [4, 4, 4, 5, 5, 5],
 [4, 4, 4, 5, 5, 5],
 [4, 4, 4, 5, 5, 5],
 [4, 4, 4, 5, 5, 5]]

In [91]:
m = 3
n = 3

rows = 5
cols = 5

# dp = [[x for x in range(m)] for x in range(n)]
dp=[[0] * cols]* rows

dp

[[0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0]]

In [16]:
import numpy as np
dp = np.asarray(dp)
dp

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [100]:
def editDistDP(str1, str2, m, n): 
    # Create a table to store results of subproblems 
    dp = [[0 for x in range(n+1)] for x in range(m+1)] 
  
    # Fill d[][] in bottom up manner 
    for i in range(m+1): 
        for j in range(n+1): 
  
            # If first string is empty, only option is to 
            # insert all characters of second string 
            if i == 0: 
                dp[i][j] = j    # Min. operations = j 
  
            # If second string is empty, only option is to 
            # remove all characters of second string 
            elif j == 0: 
                dp[i][j] = i    # Min. operations = i 
  
            # If last characters are same, ignore last char 
            # and recur for remaining string 
            elif str1[i-1] == str2[j-1]: 
                dp[i][j] = dp[i-1][j-1] 
  
            # If last character are different, consider all 
            # possibilities and find minimum 
            else: 
                dp[i][j] = 1 + min(dp[i][j-1],        # Insert 
                                   dp[i-1][j],        # Remove 
                                   dp[i-1][j-1])    # Replace 
    print(np.asarray(dp))
    return dp[m][n] 

In [101]:
str1 = "sunday"
str2 = "saturday"
  
print(editDistDP(str1, str2, len(str1), len(str2))) 

[[0 1 2 3 4 5 6 7 8]
 [1 0 1 2 3 4 5 6 7]
 [2 1 1 2 2 3 4 5 6]
 [3 2 2 2 3 3 4 5 6]
 [4 3 3 3 3 4 3 4 5]
 [5 4 3 4 4 4 4 3 4]
 [6 5 4 4 5 5 5 4 3]]
3
